DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  author VARCHAR(255),
  img VARCHAR(255),
  descrip VARCHAR,
  ISBN VARCHAR(255),
  bookshelf VARCHAR(255)
);